//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by fdms2view.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_fdms2viewTYPE               129
#define IDD_DIALOG_FDMSPROP             130
#define ID_VIEW_FDMS2PROPERTIES         131
#define IDD_DIALOGMetr                  132
#define ID_VIEW_TEMPOMAP                133
#define ID_VIEW_PROGRAM1                134
#define ID_VIEW_PROGRAM2                135
#define ID_VIEW_PROGRAM3                136
#define ID_VIEW_PROGRAM4                137
#define ID_VIEW_PROGRAM5                138
#define IDD_DIALOG_FRAG                 139
#define ID_VIEW_FRAGMENTMAP             140
#define ID_EXPORT_EIGHTWAV              141
#define IDD_DIALOG_EXPORT               142
#define IDR_TOOLBAR_TRANSPORT           143
#define ID_VIEW_ZOOM                    145
#define ID_ZOOM_1                       146
#define ID_ZOOM_2                       147
#define ID_ZOOM_FULL                    148
#define ID_VIEW_ZOOMY                   149
#define ID_ZOOMY_MAX                    150
#define ID_ZOOMY_12DB                   151
#define ID_ZOOMY_24DB                   152
#define IDD_DIALOG_MIX1                 153
#define ID_VIEW_MIX                     154
#define ID_EDIT_PLAY                    155
#define ID_EDIT_STOP                    156
#define ID_DEVICE_SOUNDCARD             157
#define IDD_DIALOG_AUDIODEVICE          158
#define IDD_DIALOG_GRAB                 159
#define IDD_DIALOG_NEW                  160
#define IDB_BITMAP1                     161
#define IDB_BITMAP_BN_R                 165
#define IDB_BITMAP3                     166
#define IDB_BITMAP_BN_P                 166
#define IDC_EDIT_FileName               1001
#define IDC_BUTTON_FN_Browse            1002
#define IDC_LIST_METR                   1004
#define IDC_EDIT1                       1005
#define IDC_EDIT2                       1006
#define IDC_EDIT_BAR                    1007
#define IDC_EDIT_Q                      1008
#define IDC_EDIT_MBAR                   1009
#define IDC_BUTTON_MADD                 1010
#define IDC_LIST_TEMPO                  1011
#define IDC_EDIT_Q2                     1012
#define IDC_EDIT_TEMPO                  1013
#define IDC_BUTTON_TADD                 1014
#define IDC_LIST_FRAG                   1015
#define IDC_PROGRESS1                   1018
#define IDC_EDIT_PREFIX                 1019
#define IDC_PROGRESS2                   1019
#define IDC_CHECK1                      1020
#define IDC_PROGRESS3                   1020
#define IDC_CHECK2                      1021
#define IDC_PROGRESS4                   1021
#define IDC_CHECK3                      1022
#define IDC_PROGRESS5                   1022
#define IDC_CHECK4                      1023
#define IDC_PROGRESS6                   1023
#define IDC_CHECK5                      1024
#define IDC_PROGRESS7                   1024
#define IDC_CHECK6                      1025
#define IDC_PROGRESS8                   1025
#define IDC_CHECK7                      1026
#define IDC_PROGRESS9                   1026
#define IDC_CHECK8                      1027
#define IDC_PROGRESS10                  1027
#define IDC_CHECKALL                    1029
#define IDC_COMBO1                      1030
#define IDC_SLIDER1                     1031
#define IDC_SLIDER2                     1032
#define IDC_COMBO2                      1032
#define IDC_CAPTURE_DEVICE_COMBO        1032
#define IDC_SLIDER3                     1033
#define IDC_SOUND_DEVICE_COMBO          1033
#define IDC_SLIDER4                     1034
#define IDC_EDIT_MTCO_H                 1034
#define IDC_SLIDER5                     1035
#define IDC_EDIT_MTCO_M                 1035
#define IDC_SLIDER6                     1036
#define IDC_SLIDER7                     1037
#define IDC_EDIT_MTCO_S                 1037
#define IDC_SLIDER8                     1038
#define IDC_EDIT_MTCO_F                 1038
#define IDC_EDIT_MTCO_SF                1039
#define IDC_SLIDER9                     1039
#define IDC_RADIO1                      1040
#define IDC_RADIO2                      1041
#define IDC_RADIO3                      1042
#define IDC_OUT_LPOS                    1043
#define IDC_OUT_LPOS_REMAIN             1044
#define IDC_STATIC_TIME_REMAIN          1045
#define IDC_OUT_TIME_REMAIN             1045
#define IDC_COMBO_BUFFEROUTSIZE         1047
#define IDC_BUTTON_LIST                 1048
#define IDC_BUTTON_GRAB                 1049
#define IDC_COMBO_LIST                  1050
#define IDC_BUTTON_OUT_BROWSE           1051
#define IDC_EDIT_OUT_FILE               1052
#define IDC_STATIC_PROGRESS             1053
#define IDC_BUTTON_STOP                 1054
#define IDC_RADIO4                      1055
#define IDC_RADIO5                      1056
#define IDC_StaticIcon                  1057
#define IDC_CHECK_SHUTDOWN              1058
#define IDC_LIST_DISK                   1059
#define IDC_BUTTON_REFRESH              1060
#define ID_BUTTON_FDMSPROP              32771
#define ID_BUTTON_TP_REC                32772
#define ID_BUTTON_TP_STOP               32775
#define ID_BUTTON_TP_PLAY               32776
#define ID_BUTTON_TP_REW                32777
#define ID_BUTTON_TP_FF                 32778
#define ID_BUTTON_MAP                   32780
#define ID_VIEW_MODE                    32782
#define ID_VIEW_MODE32783               32783
#define ID_VIEW_DB                      32784
#define ID_BUTTON_TP_END                32787
#define ID_BUTTON_TP_BEGIN              32788
#define ID_EDIT_PLAY_TOGGLE             32791
#define ID_EXPORT_MULTITRACK            32793
#define ID_DEVICE_GRAB                  32794
#define ID_VIEW_RECREATEPEEKFILE        32795
#define ID_DEVICE_QUICKFORMAT           32801
#define ID_EDIT_SELECTALL               32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
